### PR TITLE
+ WNDR3700v1 --- not tested yet

### PR DESCRIPTION
**Pull request by aeickho**
hi flokll,
   with this patch also WNDR3700v1 works fine.

-alex

### CODE REVIEW

**Comment by flokli** [comment]
Hi aeickho,

how thoroughly did you test all functions? I could add it to my pull request at https://github.com/freifunk-gluon/gluon/pull/265, but your commit message still says it's untested...

flokli

**Comment by aeickho** [comment]
this was the commit message for bilding, befor test.

basic wifi meshing with neighbouring nodes
--> tested, with TL-WR841N/ND v9 only 2.4GHz

client WLAN (if applicable)
--> works

client lan on LAN ports (if applicable)
--> works

mesh-vpn on WAN port
--> works

mesh-on-wan
--> Not tested

re-entering configmode by pressing the button for >3 seconds
--> works

entering failsafe mode
works

whether the MAC address seen by Gluon is the one printed on the device
--> yes

lua -e "print(require('platform_info').get_image_name())"
--> netgear-wndr3700





alex_test-01

Model: NETGEAR WNDR3700
Firmware release: 0.6_ae3+exp20150112

16:39:45 up 10 min,  load average: 0.07, 0.09, 0.06

8: br-client: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue 
    link/ether xxxxxxxxxx brd ff:ff:ff:ff:ff:ff
    inet6 fde6:36fc:c985:xxxxxxxxxxx/64 scope global dynamic 
       valid_lft 86342sec preferred_lft 14342sec
    inet6 fe80::3246xxxxxxxxxx/64 scope link 
       valid_lft forever preferred_lft forever

             total         used         free       shared      buffers
Mem:         61348        29672        31676            0         2220
-/+ buffers:              27452        33896
Swap:            0            0            0

Filesystem           1K-blocks      Used Available Use% Mounted on
/dev/root                 2304      2304         0 100% /rom
/dev/mtdblock5            4288       300      3988   7% /overlay

Neighbours
wlan1

Joined IBSS 74:19:87:21:ea:1c (on wlan1)
	SSID: mesh.ffgoe
	freq: 5220


wlan0

Joined IBSS 74:19:87:21:ea:1c (on wlan0)
	SSID: mesh.ffgoe
	freq: 2412

Station ************** (on wlan0)
	inactive time:	20 ms
	rx bytes:	4641219
	rx packets:	19573
	tx bytes:	1497411
	tx packets:	3657
	tx retries:	31
	tx failed:	0
	signal:  	-29 [-30, -36] dBm
	signal avg:	-29 [-30, -36] dBm
	tx bitrate:	300.0 MBit/s MCS 15 40MHz short GI
	rx bitrate:	300.0 MBit/s MCS 15 40MHz short GI
	authorized:	yes
	authenticated:	yes
	preamble:	long
	WMM/WME:	yes
	MFP:		no
	TDLS peer:	no
Station ************* (on wlan0)
	inactive time:	70 ms
	rx bytes:	989614
	rx packets:	14210
	tx bytes:	815
	tx packets:	17
	tx retries:	0
	tx failed:	0
	signal:  	-49 [-50, -56] dBm
	signal avg:	-49 [-50, -57] dBm
	tx bitrate:	54.0 MBit/s MCS 9 40MHz
	rx bitrate:	5.5 MBit/s
	authorized:	yes
	authenticated:	yes
	preamble:	long
	WMM/WME:	yes
	MFP:		no
	TDLS peer:	no

VPN status

fastd running for 586.789 seconds
There are 1 peers configured, of which 1 are connected:

mesh_vpn_backbone_peer_vpn1: connected for 548.425 seconds

**Comment by flokli** [comment]
cherry-picked your commit with changed commit message into my branch. It is now part of https://github.com/freifunk-gluon/gluon/pull/265

Thanks!

**Comment by flokli** [comment]
@aeickho the "parent pull request " got merged into the gluon main repository :-)

**Pull request closed without merging**
